name: flutter_reaction_button
description: Flutter button reaction it is fully customizable widget such as Facebook reaction button
version: 2.0.1+1
homepage: https://github.com/GeekAbdelouahed/flutter-reaction-button
repository: https://github.com/GeekAbdelouahed/flutter-reaction-button.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: